#In order to validate that the secret is available to the pod, exec into container and use 'env' or 'printenv' 
#and you will be able to see SECRET_CREDENTIAL with its value in clear text

#kubectl exec -it secret-envars-test-pod -- /bin/bash
#env

apiVersion: v1
kind: Pod
metadata:
   name: secret-envars-test-pod
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: SECRET_CREDENTIAL
      valueFrom:
       secretKeyRef:
         name: test-secret
         key: Credential
