apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
     app: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
#      nodeSelector:
#        app: nginxds
      containers:
      - name: webserver-nginx
        image: nginx
        ports:
        - containerPort: 80
